services:
  ui:
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - .:/barbeariafront
    command: ng serve --host 0.0.0.0
    stdin_open: true
    networks:
      - barbearia-api-net

networks:
  barbearia-api-net:
    name: barbearia-api-net
    external: true